    export const contactConstants={

    GET_ALL_CONTACTS_REQUEST : 'GET_ALL_CONTACTS_REQUEST',
    GET_ALL_CONTACTS_SUCCESS : 'GET_ALL_CONTACTS_SUCCESS',
    GET_ALL_CONTACTS_FAILURE : 'GET_ALL_CONTACTS_FAILURE',

}